# See https://docs.docker.com/compose/compose-file/ for information about what
# commands you can use in this file.
#
# Note that you must use the `docker stack deploy` command, with any required
# command line flags, in order to actually get any replicas started. That
# command requires that a docker swarm is already running in order to function.

version: "3"
services:
  bootstrappingNode:
    image: bootstrap:latest
    #volumes: 
    # - ./:/BootstrappingNode
    #command: touch /src/BootstrappingNode/bootstrap
    networks:
      kademlia_network:
        ipv4_address: 172.18.0.3
  kademliaNodes:
    image: kadlab:latest # Make sure your Docker image has this name.
    depends_on:
      - "bootstrappingNode"
    stdin_open: true
    tty: true
    deploy:
      mode: replicated
      replicas: 0
#        resources:
#           limits:
#              cpus: "0.1"
#              memory: 50M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
#    ports:
#      - "4000:80"
    networks:
      - kademlia_network
       
networks:
  kademlia_network:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16